package dbfiller;
// Generated Apr 2, 2014 5:48:38 PM by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * City generated by hbm2java
 */
public class City  implements java.io.Serializable {


     private BigDecimal cityId;
     private String cityName;
     private String country;
     private Set teams = new HashSet(0);

    public City() {
    }

	
    public City(BigDecimal cityId) {
        this.cityId = cityId;
    }
    public City(BigDecimal cityId, String cityName, String country, Set teams) {
       this.cityId = cityId;
       this.cityName = cityName;
       this.country = country;
       this.teams = teams;
    }
   
    public BigDecimal getCityId() {
        return this.cityId;
    }
    
    public void setCityId(BigDecimal cityId) {
        this.cityId = cityId;
    }
    public String getCityName() {
        return this.cityName;
    }
    
    public void setCityName(String cityName) {
        this.cityName = cityName;
    }
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }
    public Set getTeams() {
        return this.teams;
    }
    
    public void setTeams(Set teams) {
        this.teams = teams;
    }




}


