package dbfiller;
// Generated Apr 2, 2014 5:48:38 PM by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Coach generated by hbm2java
 */
public class Coach  implements java.io.Serializable {


     private BigDecimal coachId;
     private String firstname;
     private String lastname;
     private Date birthdate;
     private String country;
     private Set teams = new HashSet(0);

    public Coach() {
    }

	
    public Coach(BigDecimal coachId) {
        this.coachId = coachId;
    }
    public Coach(BigDecimal coachId, String firstname, String lastname, Date birthdate, String country, Set teams) {
       this.coachId = coachId;
       this.firstname = firstname;
       this.lastname = lastname;
       this.birthdate = birthdate;
       this.country = country;
       this.teams = teams;
    }
   
    public BigDecimal getCoachId() {
        return this.coachId;
    }
    
    public void setCoachId(BigDecimal coachId) {
        this.coachId = coachId;
    }
    public String getFirstname() {
        return this.firstname;
    }
    
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }
    public String getLastname() {
        return this.lastname;
    }
    
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }
    public Date getBirthdate() {
        return this.birthdate;
    }
    
    public void setBirthdate(Date birthdate) {
        this.birthdate = birthdate;
    }
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }
    public Set getTeams() {
        return this.teams;
    }
    
    public void setTeams(Set teams) {
        this.teams = teams;
    }




}


