package dbfiller;
// Generated Apr 2, 2014 5:48:38 PM by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.Date;

/**
 * PlayInTeam generated by hbm2java
 */
public class PlayInTeam  implements java.io.Serializable {


     private PlayInTeamId id;
     private Team team;
     private Player player;
     private Date toDate;
     private String position;
     private BigDecimal squadNumber;
     private Character isCaptain;

    public PlayInTeam() {
    }

	
    public PlayInTeam(PlayInTeamId id, Team team, Player player) {
        this.id = id;
        this.team = team;
        this.player = player;
    }
    public PlayInTeam(PlayInTeamId id, Team team, Player player, Date toDate, String position, BigDecimal squadNumber, Character isCaptain) {
       this.id = id;
       this.team = team;
       this.player = player;
       this.toDate = toDate;
       this.position = position;
       this.squadNumber = squadNumber;
       this.isCaptain = isCaptain;
    }
   
    public PlayInTeamId getId() {
        return this.id;
    }
    
    public void setId(PlayInTeamId id) {
        this.id = id;
    }
    public Team getTeam() {
        return this.team;
    }
    
    public void setTeam(Team team) {
        this.team = team;
    }
    public Player getPlayer() {
        return this.player;
    }
    
    public void setPlayer(Player player) {
        this.player = player;
    }
    public Date getToDate() {
        return this.toDate;
    }
    
    public void setToDate(Date toDate) {
        this.toDate = toDate;
    }
    public String getPosition() {
        return this.position;
    }
    
    public void setPosition(String position) {
        this.position = position;
    }
    public BigDecimal getSquadNumber() {
        return this.squadNumber;
    }
    
    public void setSquadNumber(BigDecimal squadNumber) {
        this.squadNumber = squadNumber;
    }
    public Character getIsCaptain() {
        return this.isCaptain;
    }
    
    public void setIsCaptain(Character isCaptain) {
        this.isCaptain = isCaptain;
    }




}


