package dbfiller;
// Generated Apr 2, 2014 5:48:38 PM by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Team generated by hbm2java
 */
public class Team  implements java.io.Serializable {


     private BigDecimal teamId;
     private Manager manager;
     private Coach coach;
     private City city;
     private String name;
     private Set playInTeams = new HashSet(0);

    public Team() {
    }

	
    public Team(BigDecimal teamId) {
        this.teamId = teamId;
    }
    public Team(BigDecimal teamId, Manager manager, Coach coach, City city, String name, Set playInTeams) {
       this.teamId = teamId;
       this.manager = manager;
       this.coach = coach;
       this.city = city;
       this.name = name;
       this.playInTeams = playInTeams;
    }
   
    public BigDecimal getTeamId() {
        return this.teamId;
    }
    
    public void setTeamId(BigDecimal teamId) {
        this.teamId = teamId;
    }
    public Manager getManager() {
        return this.manager;
    }
    
    public void setManager(Manager manager) {
        this.manager = manager;
    }
    public Coach getCoach() {
        return this.coach;
    }
    
    public void setCoach(Coach coach) {
        this.coach = coach;
    }
    public City getCity() {
        return this.city;
    }
    
    public void setCity(City city) {
        this.city = city;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getPlayInTeams() {
        return this.playInTeams;
    }
    
    public void setPlayInTeams(Set playInTeams) {
        this.playInTeams = playInTeams;
    }




}


